#theme: jekyll-theme-time-machine
remote_theme: pages-themes/time-machine@v0.2.0
title: [Crazy Walterke]
description: [...]
google_analytics: [G-PBFRZ8HL7S]
github:
  repository_url: https://github.com/crazywalterke
